heat_template_version: 2015-04-30

description: HOT template to deploy ENIQ Stack in Openstack cloud.

parameters:
    instance_ip:
        type: string
        description: IP of port with which instance get created.
        default: 10.210.243.102

    instance_name:
        type: string
        description: Name of the instance to be created.
        default: eniq_medium

    key_name:
        type: string
        description: Name of an existing key pair to enable SSH access to the instance.
        default: eniqs_key

    availability_zone:
        type: string
        description: The Availability Zone to launch the instance.
        default: nova

    volume_size:
        type: number
        description: Size of the volume to be created.
        default: 1
        constraints:
          - range: { min: 1, max: 700 }
            description: must be between 1 and 700 Gb.

resources:

    testsrv_1:
         type: OS::Nova::Server
         properties:
            availability_zone: { get_param: availability_zone }
            name: { get_param: instance_name }
            image: ENIQ_RHEL7.6_ROOT
            flavor: eniq_standard
            key_name: { get_resource: key_pair }
            networks:
            - port: { get_resource: ENIQ_PORT }

    key_pair:
        type: OS::Nova::KeyPair
        properties:
            save_private_key: true
            name: { get_param: key_name }
      
    ENIQ_PORT:
        type: OS::Neutron::Port
        properties:
            network_id: 6eceb18a-8101-4bc2-94c3-3006de31145e 
            fixed_ips: [{"subnet_id": 93897857-5d04-4964-a8d6-f58561ccd2ed, "ip_address": { get_param: instance_ip }}]
            security_groups: [{ get_resource: server_security_group }]

    server_security_group:
        type: OS::Neutron::SecurityGroup
        properties:
            description: Add security group rules for server
            name: security-group
            rules:
                - remote_ip_prefix: 0.0.0.0/0
                  protocol: tcp
                  port_range_min: 22
                  port_range_max: 22

    cinder_volume:
        type: OS::Cinder::Volume
        properties:
            size: { get_param: volume_size }
            availability_zone: { get_param: availability_zone }

    volume_attachment:
        type: OS::Cinder::VolumeAttachment
        properties:
            volume_id: { get_resource: cinder_volume }
            instance_uuid: { get_resource: testsrv_1 }
            mountpoint: /dev/sdb

outputs:

    instance_ip:
        description: IP address of the instance.
        value: { get_attr: [ testsrv_1, first_address ] }

    instance_name:
        description: Name of the instance.
        value: { get_attr: [ testsrv_1, name ] }